### ISSUE TITLE
ModuleNotFoundError: No module named 'core'

### ISSUE THREAD

**Issue by guppy57** [lukaskubis/darkskylib#4]
I copied and pasted the bottom sample code, and each time I try to run it I keep getting this error

`ModuleNotFoundError: No module named 'core'
`
I am running python 3.6.3, and I tried doing 'pip install core' but nothing worked.

Is there any way to fix this?

**Comment by bfauser** [comment]
Hi, this issue is with the  __init__.py file where you should put 
``from .core import *``
This was necessary as I imported the module with pip. Btw: ``from foo import *`` is a very bad programming style, one should import everything explicitly or import ``as drksky`` or such.
I had to make several other changes to get at least the forecast command to work, as I use python 3.6 and a venv (if you have installed this package in a *venv* look at ``\<venv_name>\Lib\site-packages\darksky`` where you find the files. I had also problems with several other packages (e.g urllib -> had to use urllib3, and Geo which was also not able to import some stuff (replace from geo import foo to from geo import *) Yes mea culpa but I was not able to see quickly what to import and just tried to test if I can get the thing working. After that, the package is still brocken because the urls in core.py are wrong (wrong machine, wrong api, wrong parameter parsing in api string generation, wrong order of parameters in forecast call etc...) 
So after spending 1h to install and test this I probably will look for another api wrapper as this one is not mature, also one should do this as asyncio, so that the process is non-blocking ....
Maybe I come back in some time, as the stuff seems to be under active development right now.
Happy sunshine :)

**Comment by lukaskubis** [comment]
I'd like to see some tracebacks because if you haven't noticed, there is no `core.py` in this codebase so I think you're testing some different package with the `darksky` namespace @guppythegod @bfauser 

There's also neither `urllib` nor `geo` dependency, just `requests`.

**Comment by oschlueter** [comment]
`pip install darksky` does not install `darkskylib`, you have to install via `pip install darkskylib` to obtain this project.

See [darksky](https://pypi.python.org/pypi/darksky) vs. [darkskylib](https://pypi.python.org/pypi/darkskylib)

**Comment by tan199954** [comment]
pip install git+git://github.com/tkuebler/pyping
